# This is numpy tutorial

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [3]:

b = np.array([[1.0,2.0,5],[3.0,5.7,5.7],[3,4,3]])
print(b)

[[1.  2.  5. ]
 [3.  5.7 5.7]
 [3.  4.  3. ]]


In [58]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get shape mxn
a.shape

(3,)

In [6]:
b.shape

(3, 3)

In [7]:
# Get data type
a.dtype

dtype('int32')

In [8]:
# Get Size
a.itemsize

4

In [9]:
# number of elements
a.size

3

In [10]:
# number of bytes = a.size * a.itemsize
a.nbytes

12

In [11]:
b.itemsize


8

In [12]:
b.dtype

dtype('float64')

In [60]:
#Accessing / Modifying spedific elements
a = np.array([[1,2,3,4,5,6,7], [6,5,4,3,2,1,1]])
a.shape

(2, 7)

In [61]:
# Get a specific element
print(a)
print(a[1,2])
print(a[-1,2])

[[1 2 3 4 5 6 7]
 [6 5 4 3 2 1 1]]
4
4


In [15]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 2]

array([3, 4])

In [17]:
for i in a[0:2,2]:
    print(i)

3
4


In [18]:
# Getting a little more fancy
a[0, 1:-1:2]

array([2, 4, 6])

In [19]:
a

array([[1, 2, 3, 4, 5, 6, 7],
       [6, 5, 4, 3, 2, 1, 1]])

In [20]:
a[1,5] = 14

In [21]:
a[: ,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 6,  5,  5,  3,  2, 14,  1]])

# Initializing different types of arrays


In [22]:
# All 0's matrix
a = np.zeros(5)
b = np.zeros((2,3))
print(a,b)

[0. 0. 0. 0. 0.] [[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# All 1's matrix
a = np.ones(3)
b = np.ones((3,4), dtype = "int32")
print(a,b)

[1. 1. 1.] [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [24]:
# a matrix with other values , with all cells having same values
a = np.full((2,2), 98)
a

array([[98, 98],
       [98, 98]])

In [25]:
# full like - initializes a same matrix as a and fills it with the given value
a = np.full_like(a , 3)
a

array([[3, 3],
       [3, 3]])

In [26]:
# Random decimal number matrix
a = np.random.rand(4,2)
a

array([[0.76649755, 0.38338527],
       [0.86603988, 0.02206431],
       [0.53326178, 0.93723565],
       [0.5844381 , 0.0492314 ]])

In [27]:
# To get same shape as A
np.random.random_sample(a.shape)

array([[0.22495042, 0.04701136],
       [0.53757786, 0.68025295],
       [0.27440804, 0.52510563],
       [0.54385638, 0.60444624]])

In [28]:
# Random integer values 
np.random.randint(4,7, size = (3,3))

array([[4, 5, 4],
       [4, 4, 4],
       [4, 5, 5]])

In [29]:
# the isentity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# to repeat an array
a = np.array([1,2,3])
ri = np.repeat(a,3)
a = np.array([[1,2,3]])
ri2 = np.repeat(a,3,axis = 0)
print(ri, ri2)

[1 1 1 2 2 2 3 3 3] [[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
# Building an example array
output = np.ones((5,5))
z = np.zeros((3,3))
z[1, 1] = 9
output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful about copying arrays


a = np.array([1,2,3])
b = a
b[0] = 100
print(b,a)

In [32]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b,a)

[100   2   3] [1 2 3]


# mathematics

In [33]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [34]:
a + 2

array([3, 4, 5, 6])

In [35]:
a - 2

array([-1,  0,  1,  2])

In [36]:
a * 2

array([2, 4, 6, 8])

In [37]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [38]:
a += 2
a

array([3, 4, 5, 6])

In [39]:
b = np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [40]:
# To take sine of all values 
np.sin(a)
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

# Linear algebra

In [41]:
# matrix multiplication
a = np.ones((2,3))
b = np.full((3,2), 2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [42]:
# determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics


In [43]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.min(stats)

1

In [45]:
np.max(stats, axis = 1)

array([3, 6])

In [46]:
np.sum(stats)

21

In [47]:
np.sum(stats, axis = 1)

array([ 6, 15])

# Reorganizing Arrays

In [48]:
# Reshaping the matrices
before = np.array([[1,2,3,4],[5,6,7,8]])
after = before.reshape((8,1))  # number of elements should be same
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [49]:
# Vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# Horizontal stack 
h1 = np.zeros((2,4))
h2 = np.ones((2,2))

np.hstack([h1,h2])

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

# Miscellaneous 

In [51]:
# load data from a file 

filedata = np.genfromtxt('data.txt' , delimiter = ',')
filedata.astype('int32')  # to change the datatype of np array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)

# Boolean Masking and advanced indexing

In [52]:
filedata > 4  # get a boolean array for which are the values greater than 4

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [53]:
# retrive the values greater than 4 
filedata[filedata > 4]


array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [54]:
# This works because we can index with a list in NumPy 
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]]) # get the elements at 1st , 2nd and 8th index 
print(a[[True,True,False,False,False,False,True,False,True]]) # if it is true element is obtained else not

[2 3 9]
[1 2 7 9]


In [55]:
print(np.any(filedata > 4, axis = 0)) # indiacates for each column if there is atleast one value greater than 4 
print(np.any(filedata > 4, axis = 1)) # indicates for each row if there is atleast one value greater than 4 

[ True  True  True  True]
[False  True  True]


In [56]:
print(np.all(filedata > 4, axis = 0)) # indicates if all values in a column are greater than 4 
print(np.all(filedata > 4, axis = 1)) # indicates if all values in a row are greater than 4 


[False False False False]
[False  True  True]


In [57]:
# Multiple condidtions 
((filedata > 2) & (filedata < 4))

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])