# Tensorflow 

Tensorflow is an open source machine learning platform. It is owned and maintained by google and it is one of the largest machine learning libraries.

### Tensorflow has two main components
- Graphs
- Sessions 

Tensorflow works by building a graph of defined computations. Nothing is computed or stored in this graph. It is simply a way of defining the operations that have been written in the code. 

A tensorflow session allows parts of the graph to be executed. It allocates memory and resources and handles the execution of operations and computations we've defined. 

In some instances we will need to run a session to be able to execute different parts of the graph we've created earlier.

In [7]:
import tensorflow as tf

print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/sankethbk7777/anaconda3/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


## Tensors 
"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.





In [9]:
# Creating Tensors 

string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.567,tf.float32)

# These tensors have shape of 1 - which means they are scalars 
# These are rank 0 variables

### Rank/Degree of Tensors
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar.

Now we'll create some tensors of higher degrees/ranks.

In [14]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["Test","Ok"],["Test","yes"]])

print(F"rank of number = {tf.rank(number)}")
print(F"rank of rank1_tensor = {tf.rank(rank1_tensor)}")
print(F"rank of rank2_tensor = {tf.rank(rank2_tensor)}")

rank of number = 0
rank of rank1_tensor = 1
rank of rank2_tensor = 2


In [17]:
# SHape - Number of items in each dimension
# Tensorflow will try to determine the shape of a tensor but sometimes it may be unknown 

print(F"Shape of floating = {floating.shape}")
print(F"Shape of rank1_tensor = {rank1_tensor.shape}")
print(F"Shape of rank2_tensor = {rank2_tensor.shape}")


Shape of floating = ()
Shape of rank1_tensor = (1,)
Shape of rank2_tensor = (2, 2)


### Changing Shape 

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [33]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a tensor of shape [1,2,3] full of 1's
print(F"Tensor1 = \n{tensor1}")

tensor2 = tf.reshape(tensor1,[2,3,1]) # rehapes existing data to [2,3,1]
print(F"\n Tensor2 = \n{tensor2}")

tensor3 = tf.reshape(tensor2,[3,-1])  # -1 tells the tensor to calculate the size of the dimension in that place 
                                      # this will reshape the tensor to [3,2]
print(F"\n Tensor3 = \n{tensor3}")

tensor4 = tf.zeros([2,2,2]) 
print(F"\n tensor4 = \n {tensor4}")

# to flatten tensor4 to 2 dimesions 
tensor5 = tf.reshape(tensor4, [4,-1])
print(F"\n tensor5 = \n {tensor5}")

Tensor1 = 
[[[1. 1. 1.]
  [1. 1. 1.]]]

 Tensor2 = 
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]

 Tensor3 = 
[[1. 1.]
 [1. 1.]
 [1. 1.]]

 tensor4 = 
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

 tensor5 = 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### Types of Tensors 
- Variables
- Constant
- Placeholder
- SparseTensor

With the exception of the variables all the other tensors are immutable, meaning their value may not change during execution.

### TensorFlow Core Learning Algorithms
In this notebook we will walk through 4 fundemental machine learning algorithms. We will apply each of these algorithms to unique problems and datasets before highlighting the use cases of each.

The algorithms we will focus on include:
- Linear Regression
- Classification
- Clustering
- Hidden Markov Models

It is worth noting that there are many tools within TensorFlow that could be used to solve the problems we will see below. I have chosen the tools that I belive give the most variety and are easiest to use.

In [35]:
from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
from six.moves import urllib

import tensorflow.compat.v2.feature_column as fc

import tensorflow as tf

In [36]:
# Load dataset. - This is titanic dataset
dftrain = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv') # training data
dfeval = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/eval.csv') # testing data

# pop removes and returns the column from the dataframe

y_train = dftrain.pop('survived')
y_eval = dfeval.pop('survived')